name: WEB
'on':
  push:
    branches:
      - main
      - feature/**
    paths:
      - web/**
      - .github/workflows/WEB.yml

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: USE NODE.JS 
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: INSTALL NODE DEPENDENCIES
        run: |
          cd web
          npm i
      # - name: RUN TEST
      #   run: |
      #     cd web
      #     npx ng test --codeCoverage
      # - name: VALIDATE CONDITIONS OF GOOD SOFTWARE
        # run: |
        #   cd web/scripts
        #   python3 validate-coverage.py --path ../coverage/lcov-report/index.html
      - name: BUILD ENTITIES
        run: |
          cd entities
          npm run build:pipeline
      - name: BUILD
        run: |
          cd web
          npm run build
      - name: DEPLOY DEV ENVIRONMENT
        run: |
          cd web
          firebase use dev --token "${{secrets.FIREBASE_TOKEN}}"
          firebase deploy --token "${{secrets.FIREBASE_TOKEN}}" 
